### ISSUE TITLE
onScannerReady event never triggered

### ISSUE THREAD

**Issue by vertigofactory** [LivotovLabs/zxscanlib#28] opened 2015-05-16 10:49 UTC
Hi,
I'm using the 2.1.0-SNAPSHOT because I had some issues with the back button (issue #23 ).

Now the back button works, but the onScannerReady event is not triggered, so the scanner doesn't detect any barcode.

I'm using the ScannerView component into an activity (with the 2.0.1 release the scanner works, but not the back button).

could you help me? thanks!

**Comment by livotov** [comment] 2015-05-20 14:18
even the bundled demo app is not working ?

**Comment by vertigofactory** [comment] 2015-05-20 16:33
I've just tried the bundled demo app, when I open the standalone activity the camera starts but it doesn't detect any code. Trying the embedded view (in my custom app I'm using an embedded view, so it's a similar situation) a white rectangle appears with "Starting camera..." centered text.

I'm using a Samsung Galaxy Nexus with Android 4.3.

**Comment by livotov** [comment] 2015-05-20 16:57
Hm, so you even don't see the live picture from the camera ?

**Comment by vertigofactory** [comment] 2015-05-20 17:00
exactly, I can see the live picture only with the standalone activity, maybe it's a issue related to CAMView, it seems that the camera doesn't start and this event doesn't propagate itself to ZxScan

**Comment by livotov** [comment] 2015-05-20 17:05
Interesting. Just checked out from master and it works fine in both modes on my Nexus 5. You're scanning the QR code, right ?

Are you trying the master (or latest snapshot) too ?

Will check on 4.3 emulator, maybe there is some compatibility issue

**Comment by vertigofactory** [comment] 2015-05-20 17:10
Yes, I'm scanning a QR code. In my project I tried with 2.1.0-SNAPSHOT and I got the error. With the latest stable release (2.0.1) everything works except for the back button. I tried your demo app downloading the zip from github and importing the project (I think that doing this I used the latest snapshot).

Thank you so much for your help!

**Comment by vertigofactory** [comment] 2015-06-04 07:21
Hi, is there any news about this issue? I'd like to help you finding a solution but I don't know where I should start from :( thank you!

**Comment by livotov** [comment] 2015-06-04 08:49
Sorry, but was extremely busy this week. Will dig onto those issues coming weekend.

**Comment by vertigofactory** [comment] 2015-06-04 08:50
Ok, thank you again, I hope we'll find a solution! Have a nice day :)

**Comment by sukrua** [comment] 2015-06-18 08:14
Hi,

I am having the same same problem with many devices. OnScannerReady never gets called. I also tried the demo app but it did not worked either. It says "starting camera", but camera never starts.

Could you help me? thanks.

**Comment by sukrua** [comment] 2015-06-18 08:19
Hello again,

I debugged the demo app recently. As i see camera fails to start and onScannerFailed method it says "Camera initialization error : -1". Do you have any idea?

Thanks.

**Comment by Garyteck** [comment] 2015-06-18 11:44
Hi, I am also having this problem with some of my devices ( samsung galaxy tab 4 and samsung galaxy tab 2 ) : onCameraReady is never called, even though the surface displayed the camera.

It is weird because it works perfectly fine on my Nexus 7 tablet and my One plus one phone.


@livotov , would you have time to investigate this ?

**Comment by livotov** [comment] 2015-06-26 07:04
Did not find anything wrong but have an idea that you might be using not actual snapshot of the linked CAMView library. Updated snapshot versions, so please try from master now or wait for 2.1.1-SNAPSHOT which will be published later today

**Comment by vertigofactory** [comment] 2015-06-26 13:28
I've just tried the 2.1.1-SNAPSHOT (including the latest CAMView snapshot) and it doesn't work again. Also, I had to download the android support library v7:22.2.0 because Android Studio can't find this library on the web when it does the Gradle sync.

**Comment by livotov** [comment] 2015-06-26 13:30
You need to update the android SDK in order to see 7.22.2.
So you still can't open the camera ?

**Comment by vertigofactory** [comment] 2015-06-26 13:34
No, in my app the camera starts, so I can see the live picture, but the QRcode is not detected. I haven't tried yet the demo app.

**Comment by livotov** [comment] 2015-06-26 13:36
please try the demo one so we'll see if there are any difference

**Comment by vertigofactory** [comment] 2015-06-26 13:48
Ok, I've just tried the bundled demo app, if I open the standalone activity the camera starts but it doesn't detect any code. If I try the embedded view a white rectangle appears with "Starting camera..." centered text (in my custom app I'm using an embedded view, so it's a similar situation, but in my app I can see the live image).

I'm using a Samsung Galaxy Nexus with Android 4.3.

**Comment by livotov** [comment] 2015-06-26 13:49
just to check, what is the code type you're trying to read ?

**Comment by vertigofactory** [comment] 2015-06-26 13:50
It's a regular QRCode

**Comment by livotov** [comment] 2015-06-26 13:54
and one more question - is Android 4.3 is an original one or  kind of Cyanogen or similar custom build?

**Comment by vertigofactory** [comment] 2015-06-26 13:56
it's the original one provided with the phone

**Comment by livotov** [comment] 2015-06-26 14:05
hm, really strange...    will try to think what else can cause this problem

**Comment by maddie** [comment] 2015-06-29 06:20
Same problem here, with Sony Xperia Z stock 5.0.2 ROM and HTC M8 GPe stock ROM. onScannerReady() is never called, neither is onScannerFailure(). I've added logs in all four methods, only onScannerStopped() is being called upon stopScanner().

**Comment by mthoretton** [comment] 2015-06-29 21:32
Same for me (Xperia Z2 5.02 ROM stock and Galaxy Tab 4 5.02 ROM Samsung), however thanks for your work and good luck to fix that !

**Comment by Luistlvr1989** [comment] 2015-07-02 21:50
Same problem here (Moto X 2013), onScannerReady() is never called. Thanks for your hard work by the way!

**Comment by benjamij** [comment] 2015-07-06 23:43
Same problem for me...

**Comment by livotov** [comment] 2015-07-07 15:35
Well, "borrowed" my son's Moto X and finally reproduced the problem. It looks like the problem is in the memory pool feature to reduce memory consumption when getting live preview frames from the camera. Hope to get a solution later tonight and we'll test the new snapshot then.

**Comment by livotov** [comment] 2015-07-08 19:46
ok guys, this finally seems to be an issue of the neighbour CAMView project. Hold on, the cause is clear and I'll try to push RC's for both this weekend.

**Comment by tefotazo** [comment] 2015-07-09 20:57
If you use the ScannerView directly (without the ScannerFragment), onScannerReady is executed.

**Comment by benjamij** [comment] 2015-07-10 00:47
Thanks @livotov. Awesome stuff :-)

**Comment by maddie** [comment] 2015-07-10 02:57
@tefotazo actually I was using it with ScannerView in an Activity without ScannerFragment, still the same.. ;(

**Comment by JulesThuillier** [comment] 2015-08-09 14:49
I have the same problem, any updates ?

**Comment by livotov** [comment] 2015-08-11 15:24
still in progress, as busy on other tasks, unfortunately

**Comment by livotov** [comment] 2015-09-02 22:40
you can check with the https://github.com/LivotovLabs/CAMView master branch right now (please see the bundled demo app). Official readme and maven repo will be updated within a day or two

**Comment by livotov** [comment] 2015-09-03 15:56
you can check with the https://github.com/LivotovLabs/CAMView master branch right now (please see the bundled demo app). Official readme and maven repo will be updated within a day or two

General usage:

```
ScannerLiveView scanner = findViewById(R.id......);
scanner.setScannerViewEventListener(...);
scanner.startScanner();
```

**Comment by livotov** [comment] 2015-09-09 16:29
IMPORTANT INFORMATION - this project is now merged with another one, called CAMView: https://github.com/LivotovLabs/CamView

All future development of this scanner library will happen inside the CAMView repository. Please post your issues and download sources, new snapshots and releases there: https://github.com/LivotovLabs/CamView

We believe both ZXScanLib and CAMView have a lot of common (moreover, ZXScanLib depends on a CAMView), so having it as a single solid project will boost productivity and add more transparency.

All previous ZXScanLib releases will remain in the maven repo forever, so no current production apps should be affected.

**Closed by livotov** 2015-09-09 16:29 UTC
